server: dev@izenesoft.cn
remote_path: /data/sf1r-resource
local_path: ./package/resource
branch: kite-2
branch_suffix: resource
sub_modules:
    - dict
    - ad_resource
    - stress_resource
push_sub_modules:
    - dict
    - ad_resource
    - stress_resource
